### ISSUE TITLE
Invalid code after processing two NullTimeTracker rector

### ISSUE THREAD

**Issue by ayacoo** [sabbelasichon/typo3-rector#2461] opened 2021-06-19 09:58 UTC
# Bug Report

First of all, the report is only meant to report a problem. It may well be that the given code is invalid from the start.

| Subject        | Details                                                         |
| :------------- | :---------------------------------------------------------------|
| Rector version | e.g. v0.11.16 |

## Minimal PHP Code Causing Issue

```
        if (!is_object($GLOBALS['TT'])) {
            $GLOBALS['TT'] = new \TYPO3\CMS\Core\TimeTracker\NullTimeTracker;
            $GLOBALS['TT']->start();
        }
```

## Expected Behaviour

```
         if (!is_object($GLOBALS['TT'])) {
            GeneralUtility::makeInstance(TimeTracker::class)->start();
         }
```

And here is the current proposal from Rector

```
         if (!is_object($GLOBALS['TT'])) {
-            $GLOBALS['TT'] = new \TYPO3\CMS\Core\TimeTracker\NullTimeTracker;
-            $GLOBALS['TT']->start();
+            $GLOBALS['TT'] = new TimeTracker;
+            $GLOBALS['TT']->start(false;
+            GeneralUtility::makeInstance(TimeTracker::class)->start();
         }
```

Applied rules:
 * TimeTrackerGlobalsToSingletonRector (https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Breaking-73504-MakeTimeTrackerASingleton.html)
 * TimeTrackerInsteadOfNullTimeTrackerRector (https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.0/Deprecation-73185-DeprecateNullTimeTracker.html)

Hint: The closing bracket was not forgotten ;-)

**Comment by sabbelasichon** [comment] 2021-06-19 10:08
Closing this because it is a duplicate of https://github.com/sabbelasichon/typo3-rector/issues/2420. Are you instantiating the NullTimeTracker without parenthesis like so NullTimeTracker

**Comment by sabbelasichon** [comment] 2021-06-19 10:09
Super ugly bug in the PrettyPrinter. Failing test already added here: https://github.com/sabbelasichon/typo3-rector/pull/2421/files

**Closed by sabbelasichon** 2021-06-19 10:08 UTC
Labels: Bug

**Comment by ayacoo** [comment] 2021-06-19 10:31
Thanks for your feedback! :-)
