### ISSUE TITLE
Can't upgrade rector/rector 0.11.32 to later version

### ISSUE THREAD

**Issue by mkrappitz** [sabbelasichon/typo3-rector#2520] opened 2021-07-29 02:23 UTC
I tried to upgrade rector/rector 0.11.32 to a newer version starting with 0.11.33 by following command:
php74 ../bin/composer.phar global require rector/rector --dev 0.11.33
The composer upgrade works fine. But after that, a previously working call to stopped working.
Call: php74 /.config/composer/vendor/bin/rector process typo3conf/ext/template/ -c ./rector.php --dry-run --autoload-file ./autoload.php

Error message:
```php
PHP Fatal error:  Declaration of RectorPrefix20210702\Symfony\Component\DependencyInjection\Container::get(string $id, int $invalidBehavior = 1) must be compatible with RectorPrefix20210702\Symfony\Component\DependencyInjection\ContainerInterface::get($id, $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE) in /.config/composer/vendor/rector/rector/vendor/symfony/dependency-injection/Container.php on line 202
Fatal error: Declaration of RectorPrefix20210702\Symfony\Component\DependencyInjection\Container::get(string $id, int $invalidBehavior = 1) must be compatible with RectorPrefix20210702\Symfony\Component\DependencyInjection\ContainerInterface::get($id, $invalidBehavior = self::EXCEPTION_ON_INVALID_REFERENCE) in /.config/composer/vendor/rector/rector/vendor/symfony/dependency-injection/Container.php on line 202
```

Similar with 0.11.34:
```php
PHP Fatal error:  Declaration of RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory::withSingularRules(?RectorPrefix20210704\Doctrine\Inflector\Rules\Ruleset $singularRules, bool $reset = false): RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory must be compatible with RectorPrefix20210704\Doctrine\Inflector\LanguageInflectorFactory::withSingularRules($singularRules, bool $reset = false) in /.config/composer/vendor/rector/rector/vendor/doctrine/inflector/lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php on line 23
Fatal error: Declaration of RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory::withSingularRules(?RectorPrefix20210704\Doctrine\Inflector\Rules\Ruleset $singularRules, bool $reset = false): RectorPrefix20210704\Doctrine\Inflector\GenericLanguageInflectorFactory must be compatible with RectorPrefix20210704\Doctrine\Inflector\LanguageInflectorFactory::withSingularRules($singularRules, bool $reset = false) in /.config/composer/vendor/rector/rector/vendor/doctrine/inflector/lib/Doctrine/Inflector/GenericLanguageInflectorFactory.php on line 23
```

Similar with 0.11.35:
```php
PHP Fatal error:  Declaration of Ssch\TYPO3Rector\FileProcessor\TypoScript\Rector\AbstractTypoScriptRector::enterTree(array $statements): void must be compatible with RectorPrefix20210706\Helmich\TypoScriptParser\Parser\Traverser\Visitor::enterTree($statements): void in /.config/composer/vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php on line 22
Fatal error: Declaration of Ssch\TYPO3Rector\FileProcessor\TypoScript\Rector\AbstractTypoScriptRector::enterTree(array $statements): void must be compatible with RectorPrefix20210706\Helmich\TypoScriptParser\Parser\Traverser\Visitor::enterTree($statements): void in /.config/composer/vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php on line 22
```

And the upgrade to 0.11.36 is not possible due to following composer error. Could it have to do with me using composer v1?
```
user@server$ php74 ../bin/composer.phar global require rector/rector --dev 0.11.36
Changed current directory to /.config/composer
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
./composer.json has been updated
Loading composer repositories with package information
Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: phpstan/phpstan[0.12.91, 0.12.88].
    - Can only install one of: phpstan/phpstan[0.12.91, 0.12.88].
    - Can only install one of: phpstan/phpstan[0.12.91, 0.12.88].
    - rector/rector 0.11.36 requires phpstan/phpstan 0.12.91 -> satisfiable by phpstan/phpstan[0.12.91].
    - Installation request for rector/rector 0.11.36 -> satisfiable by rector/rector[0.11.36].
    - Installation request for phpstan/phpstan (locked at 0.12.88) -> satisfiable by phpstan/phpstan[0.12.88].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by DanielSiepmann** [comment] 2021-08-03 13:02
I'm facing nearly the same (posted in Slack: https://typo3.slack.com/archives/C019R5LAA6A/p1627897626001900).
Not sure if the issue is related to typo3-rector or rector/rector.

I can't use any version from >= 0.11.33 up to 0.11.42. All of them are broken with this or other error messages during execution. See above post for other errors. This is just one example, so you know how I execute:
```
./vendor/bin/rector process local_packages
PHP Fatal error:  Declaration of Ssch\TYPO3Rector\FileProcessor\TypoScript\Rector\AbstractTypoScriptRector::enterTree(array $statements): void must be compatible with RectorPrefix20210706\Helmich\TypoScriptParser\Parser\Traverser\Visitor::enterTree($statements): void in /project/vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php on line 8
Fatal error: Declaration of Ssch\TYPO3Rector\FileProcessor\TypoScript\Rector\AbstractTypoScriptRector::enterTree(array $statements): void must be compatible with RectorPrefix20210706\Helmich\TypoScriptParser\Parser\Traverser\Visitor::enterTree($statements): void in /project/vendor/rector/rector/vendor/ssch/typo3-rector/src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php on line 8
```

I guess the releases include an older version of the TypoScript Parser which didn't have the type hints. The Latest releases include them and should work fine. Not sure how I can alter the used version or check the version to provide further support.

Installation works just fine with following command, no matter which version `composer req --dev -W rector/rector:0.11.34;`

Version `0.11.32` seems to be the latest working version regarding those inner compatibility issues.

**Comment by sabbelasichon** [comment] 2021-08-03 15:53
Duplicate of https://github.com/sabbelasichon/typo3-rector/issues/2510

**Closed by sabbelasichon** 2021-08-03 15:53 UTC
Labels: Bug
