### ISSUE TITLE
Breaking: #102763 - Extbase HashService usage replaced with Core HashService

### ISSUE THREAD

**Issue by simonschaufi** [sabbelasichon/typo3-rector#4079] opened 2024-02-12 19:35 UTC
Breaking: #102763 - Extbase HashService usage replaced with Core HashService

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Breaking-102763-ExtbaseHashServiceUsageReplacedWithCoreHashService.html

---
title: "Breaking: #102763 - Extbase HashService usage replaced with
  Core HashService"
---

See [102763](https://forge.typo3.org/issues/102763)

# Description

All usages of the `@internal` class
`\TYPO3\CMS\Extbase\Security\Cryptography\HashService` in TYPO3 have
been removed and replaced by `\TYPO3\CMS\Core\Crypto\HashService`.

# Impact

Custom extensions expecting
`\TYPO3\CMS\Extbase\Security\Cryptography\HashService` as type of the
property `'$hashService` of various `@internal` classes will result in a
PHP Fatal error.

# Affected installations

TYPO3 installations with custom extensions using one of the following:

- Property `$hashService` of
  `\TYPO3\CMS\Fluid\ViewHelpers\FormViewHelper`
- `@internal` property `$hashService` of class
  `\TYPO3\CMS\Extbase\Mvc\Controller\ActionController`
- Property `$hashService` of `internal` class
  `\TYPO3\CMS\Extbase\Mvc\Controller\MvcPropertyMappingConfigurationService`
- Property `$hashService` of `internal` class
  `\TYPO3\CMS\FrontendLogin\Configuration\RecoveryConfiguration`
- Property `$hashService` of `internal` class
  `\TYPO3\CMS\FrontendLogin\Configuration\RecoveryConfiguration`
- Property `$hashService` of `internal` class
  `\TYPO3\CMS\FrontendLogin\Controller\PasswordRecoveryController`
- Property `$hashService` of `internal` class
  `\TYPO3\CMS\Form\Domain\Runtime\FormRuntime`
- Property `$hashService` of `internal` class
  `\TYPO3\CMS\Form\Mvc\Property\TypeConverter\UploadedFileReferenceConverter`

# Migration

Custom extensions must be adapted to use methods of class
`\TYPO3\CMS\Core\Crypto\HashService`.

<div class="index">

Fluid, Frontend, PHP-API, FullyScanned, ext:extbase

</div>

**Comment by sabbelasichon** [comment] 2024-03-07 10:23
This is a duplicate of https://github.com/sabbelasichon/typo3-rector/issues/4108

**Closed by sabbelasichon** 2024-03-07 10:23 UTC
Labels: Breaking, Fluid, easy pick, 13.0, 13, PHP-API, Frontend, FullyScanned, ext:extbase
